name: Publish

on:
  push:
    branches:
      - main
jobs:
  build_cli:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust: [ '1.67.1' ]
        target: [ x86_64-apple-darwin, x86_64-unknown-linux-gnu ]
        include:
          - os: macos-12
            target: x86_64-apple-darwin
            binary_path: target/x86_64-apple-darwin/release
            name: x86_64-darwin
            tar: gtar
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            binary_path: target/x86_64-unknown-linux-gnu/release
            name: x86_64-linux
            tar: tar
    steps:
      - uses: actions/checkout@v3
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.rust }}-publish-1
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
        if: contains(matrix.os, 'macos')
      - name: Build
        run: |
          cargo clean --target ${{ matrix.target }} --release
          cargo build --target ${{ matrix.target }} --locked --release
  # publish:
  #   runs-on: ubuntu-latest
  #   needs: build_cli
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       rust: [ '1.67.1' ]
  #       name: [ 'x86_64-darwin', 'x86_64-linux' ]
  #   steps:
  #     - TODO